kind: ReplicationController
apiVersion: v1
metadata:
  name: file-server
spec:
  replicas: 1
  selector:
    role: file-server
  template:
    metadata:
      labels:
        role: file-server
    spec:
      containers:
      - name: file-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: file-server-export
      volumes:
        - name: file-server-export
          persistentVolumeClaim:
            claimName: nfs-claim
